name: SCMurderMystery
version: 1.0.0
author: PerriSvK
depend: [CorpseReborn,DevTools]
main: sk.perri.murdermystery.Main
commands:
  setup:
    description: Minigame setup command
    usage: Use "/setup help" to view help
    aliases: [s]
  murder:
    description: Minigame base command
    usage: Use "/murder help" to view help
    aliases: [mm]
permissions:
  murder.*:
    default: op
  murder.swords.*:
    default: op
  murder.swords.wood_sword:
    default: op
  murder.swords.stone_sword:
    default: op
  murder.swords.iron_sword:
    default: true
  murder.swords.gold_sword:
    default: op
  murder.swords.diamond_sword:
    default: op