name: SCMurderMystery
version: 1.1.0
author: PerriSvK
softdeped: [DevTools]
depend: [Holograms]
main: sk.perri.murdermystery.MainMurder
commands:
  setup:
    description: Minigame setup command
    usage: Use "/setup help" to view help
    aliases: [s]
  murder:
    description: Minigame base command
    usage: Use "/murder help" to view help
    aliases: [mm]
  mmdebug:
    description: Bubug command for MM
    usage: Use "/mmdebug" for help
    aliases: [mmd, muderdubug]
  gadget:
    description: Gadget setup command
    usage: /gadget
    aliases: [gd]
permissions:
  murder.*:
    default: op
  murder.swords.*:
    default: op
  murder.swords.wood_sword:
    default: op
  murder.swords.stone_sword:
    default: op
  murder.swords.iron_sword:
    default: true
  murder.swords.gold_sword:
    default: op
  murder.swords.diamond_sword:
    default: op
  murder.trails.*:
    default: op
  murder.trails.heart:
    default: op
  murder.trails.spell:
    default: op
  murder.trails.witch:
    default: op
  murder.trails.flame:
    default: op
  murder.trails.lava:
    default: op
  murder.trails.totem:
    default: op
  murder.trails.note:
    default: op
  murder.trails.dmg:
    default: op
  murder.trails.slime:
    default: op
  murder.trails.snowball:
    default: op
  murder.trails.angry:
    default: op
  murder.trails.happy:
    default: op
  murder.trails.redstone:
    default: op
  murder.trails.water:
    default: op
  murder.trails.crit:
    default: op
  murder.trails.rod:
    default: op
  murder.trails.explo:
    default: op